services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ${EXTERNAL_DRIVE}/plex-me-hard/config:/config
      - ${EXTERNAL_DRIVE}/plex-me-hard/transcode:/transcode
      - ${EXTERNAL_DRIVE}/plex-me-hard/data/movies:/data/movies
      - ${EXTERNAL_DRIVE}/plex-me-hard/data/tv:/data/tv
      - ${EXTERNAL_DRIVE}/plex-me-hard/data/music:/data/music
    restart: unless-stopped

  converter:
    build: ../converter
    container_name: media-converter
    volumes:
      - ../input:/input
      - ${EXTERNAL_DRIVE}/plex-me-hard/data/movies:/output/movies
      - ${EXTERNAL_DRIVE}/plex-me-hard/data/tv:/output/tv
      - ${EXTERNAL_DRIVE}/plex-me-hard/data/music:/output/music
    environment:
      - INPUT_DIR=/input
      - OUTPUT_MOVIES=/output/movies
      - OUTPUT_TV=/output/tv
      - OUTPUT_MUSIC=/output/music
    restart: unless-stopped

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ${EXTERNAL_DRIVE}/plex-me-hard/torrent/config:/config
      - ${EXTERNAL_DRIVE}/plex-me-hard/torrent/downloads:/downloads
      - ${EXTERNAL_DRIVE}/plex-me-hard/torrent/watch:/watch
      - ../input:/input
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
